---
regions: ['P', 'U', 'J', 'K']
modules:

# Antifreeze Codes
  - name: 'Cannon Antifreeze'
    type: 'COMPILED'
    src: 'antifreeze/cannon.txt'

  - name: 'Item Spam Antifreeze'
    type: 'C2D2'
    src: 'antifreeze/itemspam.S'
    addr_p: 0x8065BBD4
    addr_u: 0x806575B8
    addr_j: 0x8065B240
    addr_k: 0x80649EEC

  - name: 'Mii Outfit C Antifreeze'
    type: 'COMPILED'
    src: 'antifreeze/miioutfitc.txt'

  - name: 'Process Invalid Track Vote'
    type: 'NOP'
    addr_p: 0x8064433C
    addr_u: 0x80612F1C
    addr_j: 0x806439A8
    addr_k: 0x80632654

  - name: 'Thwomp Antifreeze'
    type: 'COMPILED'
    src: 'antifreeze/thwomp.txt'

# CT Support
  - name: 'BRRES Anti-Flicker'
    type: 'COMPILED'
    src: 'ctsupport/brresantiflicker.txt'

  - name: 'Speed Modifier'
    type: 'COMPILED'
    src: 'ctsupport/speedmod.txt'

# Commodities
  - name: 'Auto Press A At Wii Strap Screen'
    type: 'BLR'
    addr_p: 0x800077C8
    addr_u: 0x800077C8
    addr_j: 0x800077C8
    addr_k: 0x80007894

  # USA ONLY
  - type: 'COMPILED'
    src: extras/esrbskip.txt

  - name: 'Automatic BRSAR Patcher'
    type: 'C2D2'
    src: 'extras/autobrsar.S'
    addr_p: 0x80091350
    addr_u: 0x800912B0
    addr_j: 0x80091270
    addr_k: 0x800913B0

  - name: 'Change Character Between Races'
    type: 'COMPILED'
    src: 'extras/changechars.txt'

  - name: 'Disable Battle Mode Button'
    type: 'C2D2'
    src: 'extras/disablebattle.S'
    addr_p: 0x805F2E88
    addr_u: 0x80635FA4
    addr_j: 0x805F2764
    addr_k: 0x805E12A8

  - name: "Disable Toad's Factory Music Reset"
    type: 'DATA'
    data: '48000010'
    addr_p: 0x80719920
    addr_u: 0x80711A54
    addr_j: 0x80718F8C
    addr_k: 0x80707CC8

  - name: "Don't Lose VR When Disconnecting"
    type: 'NOP'
    addr_p: 0x80856560
    addr_u: 0x80834AD0
    addr_j: 0x80855BCC
    addr_k: 0x80844920

  - name: 'Instant Disconnect'
    type: 'COMPILED'
    src: 'extras/instantdc.txt'

  - name: 'License Unlocker'
    type: 'DATA'
    data: '38600001'
    addr_p: 0x80549974
    addr_u: 0x80544438
    addr_j: 0x805492F4
    addr_k: 0x805379CC

  - name: 'Points Table Modifier'
    type: 'C2D2'
    src: 'extras/points.S'
    addr_p: 0x8052EC38
    addr_u: 0x8052A0F0
    addr_j: 0x8052E5B8
    addr_k: 0x8051CC90

  - name: 'Region Lines Patch'
    type: 'COMPILED'
    src: 'extras/regionlines.S'
    addr_p: 0x806513E0
    addr_u: 0x8061E0CC
    addr_j: 0x80650A4C
    addr_k: 0x8063F6F8

  - name: 'Silent Controller Changing'
    type: 'NOP'
    addr_p: 0x8061AF98
    addr_u: 0x805EAF5C
    addr_j: 0x8061A70C
    addr_k: 0x806093B8

# Online Stuff
  - name: 'Region Changer'
    type: 'COMPILED'
    src: 'online/regionpatch.txt'

  - name: 'Remove Worldwides Button'
    type: 'COMPILED'
    src: 'online/nowwbutton.txt'

  - name: 'Wiimmfi'
    type: 'COMPILED'
    src: 'online/wiimmfi.txt'

# Important Codes
  - name: '30 Second Time Limit Modifier'
    type: 'DATA'
    data: '2A30'
    addr_p: 0x8053EC8E
    addr_u: 0x80539752
    addr_j: 0x8053E60E
    addr_k: 0x8052CCE6

  - name: 'All Items Can Land'
    type: '0616'
    addr_p: 0x80001600
    addr_u: 0x80001600
    addr_j: 0x80001600
    addr_k: 0x80001600

  - name: 'Blooper Invincibility'
    type: 'BLR'
    addr_p: 0x807A92B0
    addr_u: 0x807D6070
    addr_j: 0x807A891C
    addr_k: 0x80797670

  - name: 'Blue Shell Speed Modifier'
    type: 'DATA'
    data: '4482'
    addr_p: 0x808A5BC4
    addr_u: 0x808A10EE
    addr_j: 0x808A4D24
    addr_k: 0x80894024

  - name: 'Blue Shell Timer'
    type: 'C2D2'
    src: 'bluetimer.S'
    addr_p: 0x807AE8A8
    addr_u: 0x807A3C00
    addr_j: 0x807ADF14
    addr_k: 0x8079CC68

  - name: 'Bullet Bill Speed Modifier'
    type: 'DATA'
    data: '435C'
    addr_p: 0x808B59F8
    addr_u: 0x808B1138
    addr_j: 0x808B4B58
    addr_k: 0x808A3E70
    
    type: 'COMPILED'
    src: 'billcannonfix.txt'

  - name: 'DC Bug Fix'
    type: 'DATA'
    data: '38E40032'
    addr_p: 0x8053F6C4
    addr_u: 0x8053A188
    addr_j: 0x8053F044
    addr_k: 0x8052D71C

  - name: 'Disable Item Poof'
    type: 'BLR'
    addr_p: 0x807A6C14
    addr_u: 0x8079DC08
    addr_j: 0x807A6280
    addr_k: 0x80794FD4

  - name: 'Final Lap Music Trigger Modifier'
    type: 'DATA'
    data: '281F0002'
    addr_p: 0x8070B2D0
    addr_u: 0x8070492C
    addr_j: 0x8070A93C
    addr_k: 0x806F9678

  - name: 'Green Shell Speed Modifier'
    type: 'DATA'
    data: '4320'
    addr_p: 0x808A5DBC
    addr_u: 0x808A12E4
    addr_j: 0x808A4F1C
    addr_k: 0x8089421C

  - name: 'Lap Distance Checker'
    type: 'C0'
    src: 'antilapper.S'

  - name: 'Motion-Sensor Bomb'
    type: 'DATA'
    src: 'motion-sensor_bomb.txt'

  - name: 'No Bullet Bill Icon'
    type: 'NOP'
    addr_p: 0x807BA5D0
    addr_u: 0x807ABB70
    addr_j: 0x807B9C3C
    addr_k: 0x807A8990

  - name: 'Remove Mushroom Bug'
    type: 'DATA'
    data: '00'
    addr_p: 0x807BA077
    addr_u: 0x807AB617
    addr_j: 0x807B96E3
    addr_k: 0x807A8437

  - name: 'Replace Blooper with Triple FIBs'
    type: 'COMPILED'
    src: 'blooper_to_fibs.txt'

  - name: "Show Everyone's Times After Race"
    type: 'COMPILED'
    src: 'show_times.txt'

  - name: 'Starting Lap Modifier'
    type: 'C2D2'
    src: 'lapmod.S'
    addr_p: 0x807F84F8
    addr_u: 0x807ED9F8
    addr_j: 0x807F7B64
    addr_k: 0x807E68B8

  - name: 'Time Limit Modifier'
    type: 'COMPILED'
    src: 'time_limit.txt'

  - name: 'Ultimate Item Randomizer'
    type: 'C2D2'
    src: 'ultimate_item_randomizer.S'
    addr_p: 0x809C3670
    addr_u: 0x809BEE68
    addr_j: 0x809C26D0
    addr_k: 0x809B1CB0

  - name: 'Ultra UnCut'
    type: 'COMPILED'
    src: 'ultra_uncut.txt'

  - name: 'Wooden Box Respawn Modifier'
    type: 'COMPILED'
    src: 'wooden_box_respawn.txt'

# Cycle Fixes
  - name: 'Cycle Fix - Coconut Mall'
    type: 'C2D2'
    src: 'cyclefixes/coconutmall.S'

  - name: 'Cycle Fix - Dry Dry Ruins'
    type: 'C2D2'
    src: 'cyclefixes/drydryruins.S'

  - name: 'Cycle Fix - Ghost Valley 2'
    type: 'DATA'
    data: '03C0'
    addr_p: 0x8080ADEE
    addr_u: 0x807F9DCE
    addr_j: 0x8080A45A
    addr_k: 0x807F91AE

  - name: "Cycle Fix - Toad's Factory"
    type: 'C2D2'
    src: 'cyclefixes/toadfactory.S'
