---
regions: ['P', 'U', 'J', 'K']
modules:

# Important Codes
  - name: '30 Second Time Limit Modifier'
    type: 'DATA'
    data: '2A30'
    addr_p: 0x8053EC8E
    addr_u: 0x80539752
    addr_j: 0x8053E60E
    addr_k: 0x8052CCE6

  - name: 'All Items Can Land'
    type: '0616'
    src: 'allitemscanland.S'
    addr_p: 0x80001600
    addr_u: 0x80001600
    addr_j: 0x80001600
    addr_k: 0x80001600

  - name: 'Blue Shell Speed Modifier'
    type: 'DATA'
    data: '4482'
    addr_p: 0x808A5BC4
    addr_u: 0x808A10EE
    addr_j: 0x808A4D24
    addr_k: 0x80894024

  - name: 'Blue Shell Timer'
    type: 'C2D2'
    src: 'bluetimer.S'
    addr_p: 0x807AE8A8
    addr_u: 0x807A3C00
    addr_j: 0x807ADF14
    addr_k: 0x8079CC68

  - name: 'Bullet Bill Speed Modifier'
    type: 'DATA'
    data: '435C'
    addr_p: 0x808B59F8
    addr_u: 0x808B1138
    addr_j: 0x808B4B58
    addr_k: 0x808A3E70

  - name: 'DC Bug Fix'
    type: 'DATA'
    data: '38E40032'
    addr_p: 0x8053F6C4
    addr_u: 0x8053A188
    addr_j: 0x8053F044
    addr_k: 0x8052D71C

  - name: 'Disable Blooper'
    type: 'COMPILED'
    src: 'noblooper.txt'

  - name: 'Disable Item Poof'
    type: 'BLR'
    addr_p: 0x807A6C14
    addr_u: 0x8079DC08
    addr_j: 0x807A6280
    addr_k: 0x80794FD4

  - name: 'Disable Timer Flashing'
    type: 'NOP'
    addr_p: 0x807F7F88
    addr_u: 0x807ED488
    addr_j: 0x807F75F4
    addr_k: 0x807E6348

  - name: "Don't Hide Position After Race"
    type: 'DATA'
    data: '38000001'
    addr_p: 0x807F4DB8
    addr_u: 0x807EA790
    addr_j: 0x807F4424
    addr_k: 0x807E3178

  - name: 'Draggable Blue Shells'
    type: 'NOP'
    addr_p: 0x807AE8A8
    addr_u: 0x807A3C00
    addr_j: 0x807ADF14
    addr_k: 0x8079CC68

  - name: 'Fast POW'
    type: 'DATA'
    data: '80'
    addr_p: 0x807B1DD3
    addr_u: 0x807D9827
    addr_j: 0x807B143F
    addr_k: 0x807A0193

  - name: 'Final Lap Music Trigger Modifier'
    type: 'DATA'
    data: '281F0002'
    addr_p: 0x8070B2D0
    addr_u: 0x8070492C
    addr_j: 0x8070A93C
    addr_k: 0x806F9678

  - name: 'Green Shell Speed Modifier'
    type: 'DATA'
    data: '4320'
    addr_p: 0x808A5DBC
    addr_u: 0x808A12E4
    addr_j: 0x808A4F1C
    addr_k: 0x8089421C

  - name: 'Increase Visual Distance'
    type: 'DATA'
    data: '4FFFFFFF'
    addr_p: 0x80892320
    addr_u: 0x8088DBE0
    addr_j: 0x80891970
    addr_k: 0x80880728

  - name: 'Inside Drift Bikes'
    type: 'C2D2'
    src: 'insidedriftbikes.S'
    addr_p: 0x80591FE8
    addr_u: 0x8058B7C4
    addr_j: 0x80591968
    addr_k: 0x80580040

  - name: 'Instant Item Boxes'
    type: 'NOP'
    addr_p: 0x80828EDC
    addr_u: 0x808153C8
    addr_j: 0x80828548
    addr_k: 0x8081729C

  - name: 'Lap Distance Checker'
    type: 'C0'
    src: 'antilapper.S'

  - name: 'Load GeoHit From Race'
    type: 'DATA'
    data: '02'
    addr_p: 0x807F92AB
    addr_u: 0x807EDEBB
    addr_j: 0x807F8917
    addr_k: 0x807E766B

  - name: 'Max Item Limit Modifier'
    type: 'COMPILED'
    src: 'delimiters.txt'

  - name: 'Mega Flips Cars'
    type: 'DATA'
    data: '01'
    addr_p: 0x8082AC03
    addr_u: 0x808170EF
    addr_j: 0x8082A26F
    addr_k: 0x80818FC3

  - name: 'Mega Mushroom Size Multiplier'
    type: 'C2D2'
    src: 'megasize.S'
    addr_p: 0x80592128
    addr_u: 0x8058B904
    addr_j: 0x80591AA8
    addr_k: 0x80580180

  - name: 'Mega Thundercloud'
    type: 'C2D2'
    src: 'megatc.S'
    addr_p: 0x80580630
    addr_u: 0x80579DCC
    addr_j: 0x8057FFB0
    addr_k: 0x8056E688

  - name: 'Motion-Sensor Bomb'
    type: 'COMPILED'
    src: 'bombpatch.txt'

  - name: 'No Bullet Bill Icon'
    type: 'NOP'
    addr_p: 0x807BA5D0
    addr_u: 0x807ABB70
    addr_j: 0x807B9C3C
    addr_k: 0x807A8990

  - name: 'No Invincibility Frames'
    type: 'C2D2'
    src: 'noinvframes.S'

  - name: 'Remove Mushroom Bug'
    type: 'DATA'
    data: '00'
    addr_p: 0x807BA077
    addr_u: 0x807AB617
    addr_j: 0x807B96E3
    addr_k: 0x807A8437

  - name: 'Replace Blooper with Triple FIBs'
    type: 'COMPILED'
    src: 'triplefibs.txt'

  - name: 'Shells Never Break'
    type: 'COMPILED'
    src: 'noshellbreak.txt'

  - name: "Show Everyone's Times After Race"
    type: 'COMPILED'
    src: 'showtimes.txt'

  - name: 'Special Item Randomizer'
    type: 'C2D2'
    src: 'specialrandomizer.S'
    addr_p: 0x80799FBC
    addr_u: 0x80790FB0
    addr_j: 0x80799628
    addr_k: 0x8078837C

  - name: 'Starting Lap Modifier'
    type: 'C2D2'
    src: 'lapmod.S'
    addr_p: 0x807F84F8
    addr_u: 0x807ED9F8
    addr_j: 0x807F7B64
    addr_k: 0x807E68B8

  - name: 'Time Limit Modifier'
    type: 'COMPILED'
    src: 'timelimit.txt'

  - name: 'Ultimate Item Randomizer'
    type: 'C2D2'
    src: 'normalrandomizer.S'
    addr_p: 0x807BA164
    addr_u: 0x807AB704
    addr_j: 0x807B97D0
    addr_k: 0x807A8524

  - name: 'Ultra UnCut'
    type: 'COMPILED'
    src: 'ultrauncut.txt'

  - name: 'Wooden Box Respawn Modifier'
    type: 'COMPILED'
    src: 'woodbox.txt'

# Cycle Fixes
  - name: 'Cycle Fix - Coconut Mall'
    type: 'C2D2'
    src: 'cyclefixes/coconutmall.S'

  - name: 'Cycle Fix - Dry Dry Ruins'
    type: 'C2D2'
    src: 'cyclefixes/drydryruins.S'

  - name: 'Cycle Fix - Ghost Valley 2'
    type: 'DATA'
    data: '03C0'
    addr_p: 0x8080ADEE
    addr_u: 0x807F9DCE
    addr_j: 0x8080A45A
    addr_k: 0x807F91AE

  - name: "Cycle Fix - Toad's Factory"
    type: 'C2D2'
    src: 'cyclefixes/toadfactory.S'

# Team stuff
  - name: 'No Team Colors'
    type: 'COMPILED'
    src: 'teams/nocolors.txt'

  - name: 'No Team Invincibility'
    type: 'DATA'
    data: '38E00000'
    addr_p: 0x8053056C
    addr_u: 0x8052BA24
    addr_j: 0x8052FEEC
    addr_k: 0x8051E5C4

# Online Stuff
  - name: 'Force 150cc'
    type: 'COMPILED'
    src: 'online/force150cc.txt'

  - name: 'Friend Room Race Count Modifier'
    type: 'COMPILED'
    src: 'online/froomraces.txt'

  - name: 'Region Changer'
    type: 'COMPILED'
    src: 'online/regionpatch.txt'

  - name: 'Remove Worldwides Button'
    type: 'COMPILED'
    src: 'online/nowwbutton.txt'

  - name: 'Wiimmfi'
    type: 'COMPILED'
    src: 'online/wiimmfi.txt'

# Antifreeze Codes
  - name: 'Cannon Antifreeze'
    type: 'COMPILED'
    src: 'antifreeze/cannon.txt'

  - name: 'Item Spam Antifreeze'
    type: 'C2D2'
    src: 'antifreeze/itemspam.S'
    addr_p: 0x8065BBD4
    addr_u: 0x806575B8
    addr_j: 0x8065B240
    addr_k: 0x80649EEC

  - name: 'Mii Outfit C Antifreeze'
    type: 'COMPILED'
    src: 'antifreeze/miioutfitc.txt'

  - name: 'Process Invalid Track Vote'
    type: 'NOP'
    addr_p: 0x8064433C
    addr_u: 0x80612F1C
    addr_j: 0x806439A8
    addr_k: 0x80632654

  - name: 'Thwomp Antifreeze'
    type: 'COMPILED'
    src: 'antifreeze/thwomp.txt'

# Commodities
  - name: 'Auto Press A At Wii Strap Screen'
    type: 'BLR'
    addr_p: 0x800077C8
    addr_u: 0x800077C8
    addr_j: 0x800077C8
    addr_k: 0x80007894

  # USA ONLY
  - type: 'COMPILED'
    src: extras/esrbskip.txt

  - name: 'Automatic BRSAR Patcher'
    type: 'C2D2'
    src: 'extras/autobrsar.S'
    addr_p: 0x80091350
    addr_u: 0x800912B0
    addr_j: 0x80091270
    addr_k: 0x800913B0

  - name: 'Change Character Between Races'
    type: 'COMPILED'
    src: 'extras/changechars.txt'

  - name: 'Disable Battle Mode Button'
    type: 'C2D2'
    src: 'extras/disablebattle.S'
    addr_p: 0x805F2E88
    addr_u: 0x80635FA4
    addr_j: 0x805F2764
    addr_k: 0x805E12A8

  - name: "Disable Toad's Factory Music Reset"
    type: 'DATA'
    data: '48000010'
    addr_p: 0x80719920
    addr_u: 0x80711A54
    addr_j: 0x80718F8C
    addr_k: 0x80707CC8

  - name: "Don't Lose VR When Disconnecting"
    type: 'NOP'
    addr_p: 0x80856560
    addr_u: 0x80834AD0
    addr_j: 0x80855BCC
    addr_k: 0x80844920

  - name: 'Instant Disconnect'
    type: 'COMPILED'
    src: 'extras/instantdc.txt'

  - name: 'License Unlocker'
    type: 'DATA'
    data: '38600001'
    addr_p: 0x80549974
    addr_u: 0x80544438
    addr_j: 0x805492F4
    addr_k: 0x805379CC

  - name: 'Points Table Modifier'
    type: 'C2D2'
    src: 'extras/points.S'
    addr_p: 0x8052EC38
    addr_u: 0x8052A0F0
    addr_j: 0x8052E5B8
    addr_k: 0x8051CC90

  - name: 'Region Lines Patch'
    type: 'C2D2'
    src: 'extras/regionlines.S'
    addr_p: 0x806513E0
    addr_u: 0x8061E0CC
    addr_j: 0x80650A4C
    addr_k: 0x8063F6F8

  - name: 'Silent Controller Changing'
    type: 'NOP'
    addr_p: 0x8061AF98
    addr_u: 0x805EAF5C
    addr_j: 0x8061A70C
    addr_k: 0x806093B8

# CT Support
  - name: 'BRRES Anti-Flicker'
    type: 'COMPILED'
    src: 'ctsupport/noflicker.txt'

  - name: 'Speed Modifier'
    type: 'COMPILED'
    src: 'ctsupport/speedmod.txt'

# Toggleables
  - name: 'Faster Menu Navigation'
    type: 'COMPILED'
    src: 'options/fastmenu.txt'

  - name: 'Mii Heads on Minimap'
    type: 'COMPILED'
    src: 'options/miiheads.txt'

  - name: 'No Music'
    type: 'COMPILED'
    src: 'options/nomusic.txt'

  - name: 'Force Battle Glitch'
    type: 'COMPILED'
    src: 'options/btglitch.txt'

  - name: 'No Character Sounds'
    type: 'COMPILED'
    src: 'options/nochars.txt'

  - name: 'Always Win Track Vote'
    type: 'COMPILED'
    src: 'options/voting.txt'
